### ISSUE TITLE
Feature Question: Any raw sql in ts files are accepted?

### ISSUE THREAD

**Issue by PorcoRosso85** [senkenn/sqlsurge#62]
Hi.
I found this explaination:

https://marketplace.visualstudio.com/items?itemName=senken.sqlsurge

---
Supporting raw SQL query

[[Prisma](https://www.prisma.io/docs/orm/prisma-client/queries/raw-database-access/raw-queries) in TypeScript
[SQLx](https://github.com/launchbadge/sqlx) in Rust

---

This means that we should use prisma if we want to make ts file autocompleted by vscode?

**Comment by senkenn** [comment]
@PorcoRosso85 Thank you for using this!!!!!!!!!

> Any raw sql in ts files are accepted?

Yes!!! I'm planning it in TODOs.
https://github.com/senkenn/sqlsurge/blob/ecd1f3cc2aa831b2a1246b30a1df6d1ea050344d/vsce/README.md?plain=1#L48

sqlsurge use AST to extract raw SQLs, so it is possible to support any ORM libraries or user-defined functions.

I'm considering the vscode settings. For example, there is a code like this,
```ts
const result = fooQueryFunc(connection, "SELECT name FROM users WHERE id = 123";
```

And `settings.json`,
```jsonc
"sqlsurge.custom": {
  "language": "typescript",
  "function": "fooQueryFunc",
  "templateLiteral": false,
  "argNum": 1 // 0-indexed
}
```

It would also be possible to handle cases where SQL is split like this,
```ts
const baseSql = "SELECT name FROM users";
const condition1 = "WHERE id = 1";
const condition2 = "WHERE id = 2";
const result = fooQueryFunc(connection, baseSql + condition1;
```
I'll support it in the future.

**Comment by senkenn** [comment]
@PorcoRosso85 
I'd like to ask you as a reference, which library are you using? Or your own functions?

**Comment by PorcoRosso85** [comment]
Own functions, maybe. No orm library.

I'm writing raw sql files as both of DDL and DML,
these files are for 'sqlc comilation for typescript' and 'sqldef migration'

I'm searching one like yours that supports us to write type safed sql in ts file.

**Comment by senkenn** [comment]
This feature will take time, but I'll do my best to release it soon!

**Comment by PorcoRosso85** [comment]
By the way, 
https://github.com/sqls-server/sqls

will sqls server work any database server if these are live? Do yo know?
https://github.com/sqls-server/sqls?tab=readme-ov-file#support-rdbms

**Comment by senkenn** [comment]
@PorcoRosso85 
I checked MySQL, Postgres only, sorry.

**Comment by PorcoRosso85** [comment]
@senkenn 

Enough.

If we use postgres, is what we only have to do is connecting live postgres server for sqls to suggest auto completion?

sqlsurge doesn't require these as sqls doc explaining?



MySQL([Go-MySQL-Driver](https://github.com/go-sql-driver/mysql))
PostgreSQL([pgx](https://github.com/jackc/pgx))
SQLite3([go-sqlite3](https://github.com/mattn/go-sqlite3))
MSSQL([go-mssqldb](https://github.com/denisenkom/go-mssqldb))
H2([pgx](https://github.com/CodinGame/h2go))
Vertica([vertica-sql-go](https://github.com/vertica/vertica-sql-go))

**Comment by senkenn** [comment]
@PorcoRosso85 Yes, connection only.

**Comment by senkenn** [comment]
@PorcoRosso85 I created new issue about this: #66
