### ISSUE TITLE
Support any libraries or user-defined functions in raw SQL (Customization)

### ISSUE THREAD

**Issue by senkenn** [senkenn/sqlsurge#66]
https://github.com/senkenn/sqlsurge/issues/62#issuecomment-2133494145

**Comment by senkenn** [comment]
available soon.

**Comment by senkenn** [comment]
- Rust implementation was completed at this commit: https://github.com/senkenn/sqlsurge/commit/c5d584835110e7ccf163f786b264d5ae4e601da9

**Comment by senkenn** [comment]
@PorcoRosso85 You can use this feature with the `sqlsurge.customRawSqlQuery` setting. This is TypeORM example.
```ts
// TypeORM in TypeScript
const someQuery = await entityManager.query(
  "SELECT * FROM todos WHERE id = $1;",
  [1]
);
```

settings.json
```json
"sqlsurge.customRawSqlQuery": {
  "language": "typescript",
  "configs": [
    {
      "functionName": "query",
      "sqlArgNo": 1,
      "isTemplateLiteral": false
    }
  ]
}
```

**Comment by PorcoRosso85** [comment]
// TypeORM in TypeScript
const someQuery = await entityManager.query(
  "SELECT * FROM todos WHERE id = $1;",
  [1]
);



ORM is not required, right? 
Is following correct? 

What I should configure sqlsurge to write raw SQL as template literal are:

- install sqlsurge
- configure sqls to connect live db server

**Comment by senkenn** [comment]
> ORM is not required, right?
> Is following correct?
>
> What I should configure sqlsurge to write raw SQL as template literal are:
>
> - install sqlsurge
> - configure sqls to connect live db server

Yes!!! All correct!

**Comment by senkenn** [comment]
Also you must set `sqlsurge.customRawSqlQuery` in settings.json
