### ISSUE TITLE
Feature Question: Restart sqls server

### ISSUE THREAD

**Issue by PorcoRosso85** [senkenn/sqlsurge#73]
Hi.

Does yours have this feature?

- Restart sqlx server
- Reload your extension

OR
Do you have plan to add this?

**Comment by senkenn** [comment]
Hi @PorcoRosso85 
sqlx server? you meen sqls?

**Comment by PorcoRosso85** [comment]
> Hi @PorcoRosso85 sqlx server? you mean sqls?

Sorry．

Yes, as you think.

**Comment by senkenn** [comment]
I think this feature would be even more useful because we will no longer need to `Reload Window`. `Reload Window` take a long time and it's annoying to wait for it.
I think a better way to achieve this would be to create a dedicated vscode command or monitor the sqls config file.
Contributions are welcome.

**Comment by senkenn** [comment]
Thanks @PorcoRosso85 for the feature suggestion.

**Comment by PorcoRosso85** [comment]
Hi.
I'm following updates of this extension.


In addition to this question, how about restarting 'sqlsurge' itself?
Do you have any plan?

**Comment by senkenn** [comment]
@PorcoRosso85 OK! I'll implement it.

**Comment by PorcoRosso85** [comment]
Thanks. 

Also sqlsurge? 
not only sqls

**Comment by senkenn** [comment]
I guess sqlsurge does not need to restart. sqlsurge does not use global storage or such as cache.
If it looks like sqlsurge will need to be restarted, I'll consider it again.

**Comment by PorcoRosso85** [comment]
Sorry if I misunderstand. 
I was thinking that we should restart sqlsurge to check whether sqlsurge has connected or searched sqls successfully. 
We don't have to restart?

**Comment by senkenn** [comment]
@PorcoRosso85 
You are not wrong.

> we should restart sqlsurge to check whether sqlsurge has connected or searched sqls successfully.

Yes, we do not have any methods to check that except for `Reload Window`.
I am trying to implement a VS Code command that immediately checks whether sqls has connected successfully.

**Comment by senkenn** [comment]
now you can get `sqlsurge.restartSqlLanguageServer` command in v0.5.8 :rocket:
