### ISSUE TITLE
sqls binary file name miss suffix in windows

### ISSUE THREAD

**Issue by MrScallion** [senkenn/sqlsurge#93]
sqls binary file name miss suffix(.exe) in windows

before I change the code, extension can not find sqls binary in windows:
![image](https://github.com/user-attachments/assets/cf86d4fa-48c6-473e-ab3c-50340990a547)

after I changed the code, extension can find sqls binary in windows:
![image](https://github.com/user-attachments/assets/2d0ea423-129b-4554-b48b-4f246da10314)

**Comment by senkenn** [comment]
@MrScallion Thanks!!! I try to support windows.

**Comment by senkenn** [comment]
windows support was released on v0.5.7.
